### ISSUE TITLE
error on autoreconf -iv

### ISSUE THREAD

**Issue by el3ctron** [dalmemail/GnuSocialShell#12]
corriendo el comando de instalación:
 (master) $ autoreconf -iv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal  --output=aclocal.m4t
Can't exec "aclocal": No existe el archivo o el directorio at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No existe el archivo o el directorio

y no puedo ejecutar el ./configure

**Comment by dalmemail** [comment]
Supongo que estás utilizando un sistema operativo basado en GNU/Linux. Instala automake:
(Debian, Ubuntu, Linux Mint, ...)
$ sudo apt-get install automake
(Fedora, CentOS, ...)
$ sudo yum install automake

Con eso debería empezar a funcionar

**Comment by el3ctron** [comment]
funcionó a la perfección! Pd. es genial ver un repo en donde puedes hablar castellano. saludos! gran pieza de sw!
