### ISSUE TITLE
Malformed request ?

### ISSUE THREAD

**Issue by Manu-sh** [dalmemail/GnuSocialShell#3]
user@arch[19:11:58]~/GnuSocialShell ⚡}➤gnusocialshell 
Error: Conecting to @translateuser@https://quitter.se/translateuserá@

My config is:
# Default Config file for GnuSocialShell

protocol=https;
user=translateuser;
server=quitter.se;
# Uncomment the line below to enable password store

password=....;

**Comment by dalmemail** [comment]
I think that maybe there is a problem with curl because the configuration file is correct and the error should be "Error: Connecting to @translateuser@quitter.se". Also when GnuSocialShell returns this fail it means that there is a problem with the XML response returned by the server.

**Comment by Manu-sh** [comment]
@dalmemail I have made a mistake, because i think that Makefile overwrite previous config file, the first time i have config my with bad variable value. When i have undestand i have edit in src dir and retype make && sudo make install (thinking that Makefile overwrites previous config installed), my config file was wrong because like:
server=quitter.se/all/translateuser;

now i have edit config file stored in my home and fix my mistake
#Default Config file for GnuSocialShell
protocol=https;
user=translateuser;
server=https://quitter.se;
#Uncomment the line below to enable password store
password=----;

but i get an error:
Error: Conecting to @translateuser@https://quitter.se
