### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by Manu-sh** [dalmemail/GnuSocialShell#4]
# Default Config file for GnuSocialShell

protocol=https;
user=translateuser;
server=https://quitter.se;
# Uncomment the line below to enable password store

password=----;

i get an error:
Error: Conecting to @translateuser@https://quitter.se

**Comment by dalmemail** [comment]
server should be "quitter.se"
server=quitter.se

**Comment by Manu-sh** [comment]
Wow, now work great, sorry but yesterday i was tired, usually I don't do those errors
